# Project 1 – To Do List

## Problem Definition

1. State the business problem.

2. Translate the business problem into a Data Science problem by stating:
-  what kind of problem it is ( supervised vs unsupervised )
- and whether it is a classification, regression, or clustering problem.

 3. Mention which model will be used, if known.

## Data Collection

2. Load Pandas, Numpy, and Matplotlib modules

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

3. Load data Train.csv from AWS S3.

In [3]:
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Project.1-Transactions/Data/Transaction.train.csv'
url

'https://ddc-datascience.s3.amazonaws.com/Projects/Project.1-Transactions/Data/Transaction.train.csv'

In [7]:
df = pd.read_csv(
    url,
    usecols=range(5),
    nrows=1_000,
)

In [8]:
df

     Unnamed: 0    ID_code  target    var_0   var_1
0             0    train_0       0   8.9255 -6.7863
1             1    train_1       0  11.5006 -4.1473
2             2    train_2       0   8.6093 -2.7457
3             3    train_3       0  11.0604 -2.1518
4             4    train_4       0   9.8369 -1.4834
..          ...        ...     ...      ...     ...
995         995  train_995       0  10.5429 -3.1313
996         996  train_996       0  12.9541 -3.5607
997         997  train_997       0   4.2341 -8.5367
998         998  train_998       0  18.5600  2.3607
999         999  train_999       0  10.5495  2.3825

[1000 rows x 5 columns]

## Data Cleaning

4. Examine the data using tools we have used in class. You should be identifying the various columns such as ...

    - target column
    - feature columns
    - identifier columns
    - null columns
    - null rows

    Tools you should be using include, but are not limited to:

    - head
    - tail
    - shape
    - size
    - info
    - describe
    - nunique
    - unique
    - isnull/isna


1. NOTE: the ‘target’ column indicates a successful transaction (‘1’) or a no-transaction (‘0’). Verify these are the only values in that column, and that there are no nulls.

target column


feature columns


identifier columns


null columns


null rows

head

In [9]:
df.head()

   Unnamed: 0  ID_code  target    var_0   var_1
0           0  train_0       0   8.9255 -6.7863
1           1  train_1       0  11.5006 -4.1473
2           2  train_2       0   8.6093 -2.7457
3           3  train_3       0  11.0604 -2.1518
4           4  train_4       0   9.8369 -1.4834

tail

In [10]:
df.tail()

     Unnamed: 0    ID_code  target    var_0   var_1
995         995  train_995       0  10.5429 -3.1313
996         996  train_996       0  12.9541 -3.5607
997         997  train_997       0   4.2341 -8.5367
998         998  train_998       0  18.5600  2.3607
999         999  train_999       0  10.5495  2.3825


shape


size


info


describe


nunique


unique


isnull/isna

1. If there are data cleaning issues, develop recommendations for how to deal with them.  Specifically, handle these common issues:

    - identifer columns
    - target column with null counts
    - feature columns with high null counts
    - feature columns with low null counts
    - feature columns with medium null counts

## Exploratory Data Analysis

Produce some visual analysis of the data.  Recall that Gaussian Naive Bayes assumes the features are normally distributed and independent. Note: you might have to do multiple plots in groups.

7. Check the distributions of all variables by plotting.

1. Check the correlation values between all **feature columns** to ensure there are no substantial correlations between features. This is important to support the decision to classify the ‘target’ using Naïve Bayes.

1. Create two data frames: one with all successful transactions, one with all unsuccessful transactions. **Make sure they are copies and not slices**.

## Data Processing

### Single Cross-validation ( CV )

10. Create two data sets: one with all the feature columns (everything except for Unnamed: 0, ID_code and target) and one with just the target. Make sure they are copies and not slices.  And make sure they are the correct dimensions.

1. Define an empty Gaussian Naïve Bayes model using Sklearn.

1. Divide the two data sets you created in step #10 into training and testing subsets, i.e. train-test split.

1. Train ( fit ) the model using the training subset of the dataset.

1. Test the model ( predict ) using the testing subset of the dataset.

1. Calculate and report the accuracy.

1. Present a confusion matrix and heatmap

1. Present the results of a Classification Report (sklearn.metrics.classification_report).

### Multiple Cross-validation ( CV )

18. Perform a cross-validation loop and record the accuracy of your model during each iteration.

1. Report the mean accuracy. How does it compare to the accuracy you calculated for the Single CV?

1. Plot a histogram of the accuracy scores you generated in your cross-validation loop. What do you notice about the distribution of accuracy scores?

1. Present a confusion matrix and heatmap

1. Present the results of a Classification Report (sklearn.metrics.classification_report).  What do you notice?  That is, how do the different metrics compare to each other?

### Balanced data set

The training data is very skewed towards non-successful transactions (about 90% of the training data has ‘target’==0).

23. Remove enough non-successful transaction rows so that your remaining training data is 50%/50% split between successful and non-successful transactions. Hint: you can use the data frames you created in step #9.

1. Repeat the multiple cross-validation process on this data set.

1. Report what your mean accuracy for this balanced data set.

1. Plot a histogram of the accuracy scores you generated in your cross-validation loop. What do you notice about the distribution of accuracy scores?

1. Present a confusion matrix and heatmap

1. Present the results of a Classification Report (sklearn.metrics.classification_report).  What do you notice?  That is, how do the different metrics compare to each other?

## Data Visualization

29. Compare the accuracy results of your multiple cross-validation with the whole training data and the balanced training data

1. Present the confusion matrix and heatmap

1. Present the results of your Classification Report (sklearn.metrics.classification_report)

## Communicate the Results

32. Communicate the results of your analysis.

## Submit Final Project

33. Save ( commit ) your finished Jupyter notebook to your Project 1 GitHub repo.