# More Indexing in Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create a data frame
my_dict = {
    'Name': ['Mary', 'Joe', 'Roger', 'Sarah', 'Mike', 'Phil'],
    'Age': [20, 45, 32, 58, 39, 42],
    'City': ['Albuquerque', 'Rio Rancho', 'Santa Fe', 'Taos', 'Albuquerque', 'Placitas'],
'Occupation': ['student', 'doctor', 'data scientist', 'general contractor', 'student', 'manager']
}
people_df = pd.DataFrame(my_dict)
people_df

    Name  Age         City          Occupation
0   Mary   20  Albuquerque             student
1    Joe   45   Rio Rancho              doctor
2  Roger   32     Santa Fe      data scientist
3  Sarah   58         Taos  general contractor
4   Mike   39  Albuquerque             student
5   Phil   42     Placitas             manager

## Review of column and row indexing

### Using column names

In [3]:
# Column indexing
people_df['Name']

0     Mary
1      Joe
2    Roger
3    Sarah
4     Mike
5     Phil
Name: Name, dtype: object

In [4]:
# Column indexing
people_df[['Name']]

    Name
0   Mary
1    Joe
2  Roger
3  Sarah
4   Mike
5   Phil

In [5]:
list_of_columns = ['Name']
people_df[ list_of_columns ]

    Name
0   Mary
1    Joe
2  Roger
3  Sarah
4   Mike
5   Phil

In [6]:
people_df['Name', 'Age']

KeyError: ('Name', 'Age')

In [7]:
# Multiple column indexing
people_df[['Name', 'Age']]

    Name  Age
0   Mary   20
1    Joe   45
2  Roger   32
3  Sarah   58
4   Mike   39
5   Phil   42

In [8]:
# Multiple column indexing
people_df[['Name', 'Age', 'Name']]

    Name  Age   Name
0   Mary   20   Mary
1    Joe   45    Joe
2  Roger   32  Roger
3  Sarah   58  Sarah
4   Mike   39   Mike
5   Phil   42   Phil

In [9]:
people_df.columns

Index(['Name', 'Age', 'City', 'Occupation'], dtype='object')

In [10]:
name_index = people_df.columns[::-2]
name_index

Index(['Occupation', 'Age'], dtype='object')

In [11]:
people_df[ name_index ]

           Occupation  Age
0             student   20
1              doctor   45
2      data scientist   32
3  general contractor   58
4             student   39
5             manager   42

In [27]:
name_index = pd.Series(people_df.columns).sample(n=3) #replace=True with replacement (after picking the first one, it has a chance of selecting the same one again)
name_index

0    Name
1     Age
1     Age
dtype: object

In [22]:
people_df[ name_index ]

          City          Occupation   Name
0  Albuquerque             student   Mary
1   Rio Rancho              doctor    Joe
2     Santa Fe      data scientist  Roger
3         Taos  general contractor  Sarah
4  Albuquerque             student   Mike
5     Placitas             manager   Phil

### Columns with iloc indices

In [28]:
# Column indexing using .iloc - indexing
people_df.iloc[:,0]

0     Mary
1      Joe
2    Roger
3    Sarah
4     Mike
5     Phil
Name: Name, dtype: object

In [29]:
# Column indexing using .iloc - slicing
people_df.iloc[:,0::2]

    Name         City
0   Mary  Albuquerque
1    Joe   Rio Rancho
2  Roger     Santa Fe
3  Sarah         Taos
4   Mike  Albuquerque
5   Phil     Placitas

In [30]:
for i in list(enumerate(people_df.columns)): #list() is not required
  print(i)

(0, 'Name')
(1, 'Age')
(2, 'City')
(3, 'Occupation')

In [31]:
# Column indexing using .iloc - list
people_df.iloc[ : , [1,0,3,2,3]]

   Age   Name          Occupation         City          Occupation
0   20   Mary             student  Albuquerque             student
1   45    Joe              doctor   Rio Rancho              doctor
2   32  Roger      data scientist     Santa Fe      data scientist
3   58  Sarah  general contractor         Taos  general contractor
4   39   Mike             student  Albuquerque             student
5   42   Phil             manager     Placitas             manager

### Rows with indices

In [34]:
# reassign index
people_df.index =  list("abcdef")
people_df

    Name  Age         City          Occupation
a   Mary   20  Albuquerque             student
b    Joe   45   Rio Rancho              doctor
c  Roger   32     Santa Fe      data scientist
d  Sarah   58         Taos  general contractor
e   Mike   39  Albuquerque             student
f   Phil   42     Placitas             manager

In [40]:
# Row indexing using .loc
people_df.loc["b"]

Name                 Joe
Age                   45
City          Rio Rancho
Occupation        doctor
Name: b, dtype: object

In [41]:
# Row indexing using .iloc
people_df.iloc[1]

Name                 Joe
Age                   45
City          Rio Rancho
Occupation        doctor
Name: b, dtype: object

In [42]:
# Multiple rows - slicing
people_df.loc["a":"c"]

    Name  Age         City      Occupation
a   Mary   20  Albuquerque         student
b    Joe   45   Rio Rancho          doctor
c  Roger   32     Santa Fe  data scientist

In [43]:
people_df.iloc[0:2]

   Name  Age         City Occupation
a  Mary   20  Albuquerque    student
b   Joe   45   Rio Rancho     doctor

In [44]:
# Selecting rows in any order - list
people_df.loc[["a","d","d","c","b"]]

    Name  Age         City          Occupation
a   Mary   20  Albuquerque             student
d  Sarah   58         Taos  general contractor
d  Sarah   58         Taos  general contractor
c  Roger   32     Santa Fe      data scientist
b    Joe   45   Rio Rancho              doctor

In [45]:
idx = [0,3,3,2,1]
idx

[0, 3, 3, 2, 1]

In [46]:
people_df.iloc[ idx, : ]

    Name  Age         City          Occupation
a   Mary   20  Albuquerque             student
d  Sarah   58         Taos  general contractor
d  Sarah   58         Taos  general contractor
c  Roger   32     Santa Fe      data scientist
b    Joe   45   Rio Rancho              doctor

### Indexing for a single entry

In [ ]:
# Row and column indexing
people_df['Name'].iloc[0]

In [ ]:
# Another way
people_df['Name'].loc["a"]

In [ ]:
# Another way
people_df.loc["a"]['Name']

In [ ]:
# Another way
people_df.loc["a"].loc['Name']

In [ ]:
# Another way
people_df.loc["a",'Name']

In [ ]:
# Another way
people_df.iloc[0,0]

In [ ]:
# Another way
people_df.iloc[0].iloc[0]

In [ ]:
# Another way
people_df.iloc[0].loc["Name"]

## Attribute Access

> WARNING: Do Not Use This

You can access columns in a dataframe as attributes. Note: there are a few cases when the attribute will not work, such as if your column is named a number (e.g., 1) or if it is named after an existing method (e.g., min).

In [ ]:
people_df

In [ ]:
people_df.Name

In [ ]:
people_df.Name.loc["a"]

In [ ]:
people_df["shape"] = 10
people_df

In [ ]:
people_df.shape

In [ ]:
people_df["shape"]

## Boolean Indexing

In [ ]:
filter = ( people_df['Age'] > 40 ) # Create a filter
filter

In [ ]:
people_df[ filter ] # Use that filter to index

In [ ]:
# Another example - people from Albuquerque
filter = ( people_df['City'] == 'Albuquerque' )
filter

In [ ]:
people_df[ filter ] # Use that filter to index

In [ ]:
# A third example! People from albuquerque or people who are doctors
filter1 = ( people_df['City'] == 'Albuquerque' )
filter1

In [ ]:
filter2 = ( people_df['Occupation'] == 'doctor' )
filter2

In [ ]:
filter = filter1 | filter2
filter

In [ ]:
# verify
pd.concat([filter1, filter2, filter, people_df], axis='columns')

In [ ]:
people_df[ filter ] # Use that filter to index

In [ ]:
# Negating
filter = ( people_df['Name'] == 'Mary' )
filter

In [ ]:
# verify
pd.concat([filter, ~filter, people_df], axis='columns')

In [ ]:
people_df[ ~filter ] # Use that filter to index

In [ ]:
people_df[people_df['Name'] != 'Mary']

## Indexing w/ Isin

In [ ]:
people_df['City']

In [ ]:
filter = ( people_df['City'].isin(['Rio Rancho', 'Santa Fe', 'Taos']) ) # Create a filter
filter

In [ ]:
# verify
pd.concat( [ filter, people_df ], axis='columns')

In [ ]:
people_df[ filter ] # Use that filter to index

## Numpy Where
The numpy where method can be useful to find rows that correspond to a particular conditional statement.

In [ ]:
import numpy as np

In [ ]:
filter = ( people_df['City'] == 'Albuquerque' )
filter

In [ ]:
where_index = np.where( filter )
where_index, where_index[0]

In [ ]:
where_index[0][1]

In [ ]:
people_df

In [ ]:
people_df.iloc[ where_index[0] ]

In [ ]:
people_df.drop( people_df.index[where_index[0]] )

In [ ]:
people_df_no_abq = people_df.drop( people_df.index[where_index[0]] )
people_df_no_abq

In [ ]:
where_index[0][0]

In [ ]:
people_df

In [ ]:
people_df.iloc[ where_index[0][0] ]

In [ ]:
people_df_no_abq

In [ ]:
people_df_no_abq.iloc[ where_index[0][0] ]

In [ ]:
people_df_no_abq.reset_index()

In [ ]:
people_df_no_abq

In [ ]:
people_df_no_abq.reset_index( drop = True )

In [ ]:
people_df_no_abq

In [ ]:
people_df_no_abq.reset_index(drop = True, inplace = True)
people_df_no_abq

## Random Sampling in Pandas

In [ ]:
people_df

In [ ]:
# Take a random sample of size 3
people_df.sample( n = 3, )

In [ ]:
# Take a random proportion
people_df.sample( frac = 1/3 )

In [ ]:
people_df.sample(n = 1)

In [ ]:
people_df.groupby('City').sample(n = 1)

In [ ]:
# Take a randoom sample but set the seed for reproducibility
people_df.sample(n = 3, random_state = 42)

In [ ]:
people_df.sample(n=2, axis="columns")

In [ ]:
people_df.sample(n=2, axis="columns").sample(n=2)